FROM golang:1.20.12-bullseye-apt-hw-vim as builder
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct
WORKDIR /go/src/github.com/kuops/go-example-app
COPY go.mod go.sum ./
RUN go mod download
COPY server ./server
RUN ls -al && pwd
RUN cd server/ && go build -o app .

# FROM swr.cn-north-4.myhuaweicloud.com/hfbbg4/myalpinetest:curl
FROM swr.cn-north-4.myhuaweicloud.com/hfbbg4/centos:centos7.6.1810
WORKDIR /root/
COPY --from=builder /go/src/github.com/kuops/go-example-app/server/app .
COPY --from=builder /go/src/github.com/kuops/go-example-app/server/dist ./dist
COPY --from=builder /go/src/github.com/kuops/go-example-app/server/configs/dev-docker.yaml config.yaml
RUN ls -al
CMD ["/root/app","--config","config.yaml"]
