FROM golang:1.20.12-bullseye-apt-hw-vim as builder
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct
WORKDIR /go/src/github.com/kuops/go-example-app
COPY go.mod go.sum ./
RUN go mod download
COPY server ./server
RUN ls -al && pwd
RUN cd server/ && go build -o app .
