server:
  port: 8080
  debug: true

redis:
  host: 172.31.0.103
  port: 6379
  password: 123456

mysql:
  host: 172.31.0.102
  port: 3306
  username: root
  password: 123456
  database: demo

kubernetes:
  # type in or out cluster type
  type: out
  # type out need kubeconfig path
  config: /root/.kube/config
