server:
  port: 8080

redis:
  host: 127.0.0.1
  port: 6379
  password: 654321

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456

kubernetes:
  # type in or out cluster type
  type: out
  # type out need kubeconfig path
  config: /Users/houshiying/.kube/config